---
abstract: 'Generate function to test a function'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Capture::Tiny: 0
  File::Slurp: 0
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gen-Test-Rinci-FuncResult
requires:
  Data::Dump::OneLine: 0
  Rinci: v1.1.37
  perl: 5.010001
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Gen-Test-Rinci-FuncResult
  homepage: https://metacpan.org/release/Gen-Test-Rinci-FuncResult
  repository: git://github.com/sharyanto/perl-Gen-Test-Rinci-FuncResult.git
version: 0.03
